name: tax_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.3
  hive: ^2.2.3
  bloc_test: ^9.1.7
  flutter_hooks: ^0.20.5
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  csv: ^6.0.0
  get_it: ^8.0.3
  rxdart: ^0.28.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  fl_chart: ^0.65.0
  provider: ^6.1.2
  flutter_launcher_icons: ^0.14.2
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/Group.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/onboarding.png
    - assets/image/Group.png
    - assets/image/google.png
