name: tax_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.3
  hive: ^2.2.3
  bloc_test: ^9.1.7
  flutter_hooks: ^0.20.5
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/onboarding.png
    - assets/image/Group.png
